# Generated by Django 6.0.2 on 2026-02-05 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='status',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='account',
            name='remaining_leaves',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(365)]),
        ),
    ]
