# Generated by Django 6.0.2 on 2026-02-07 22:07
# Modified by Aaron Mathew

import django.core.validators
from django.db import migrations, models


def copy_fields(apps, schema_editor):
    account_model = apps.get_model("account", "Account")
    account_model.objects.update(
        current_year_allocated_leaves=models.F("allocated_leaves"),
        default_allocated_leaves=models.F("allocated_leaves"),
    )


def reverse_copy_fields(apps, schema_editor):
    account_model = apps.get_model("account", "Account")
    account_model.objects.update(allocated_leaves=models.F("default_allocated_leaves"))


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="current_year_allocated_leaves",
            field=models.PositiveSmallIntegerField(
                default=20, validators=[django.core.validators.MaxValueValidator(365)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="default_allocated_leaves",
            field=models.PositiveSmallIntegerField(
                default=20, validators=[django.core.validators.MaxValueValidator(365)]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="remaining_leaves",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(365)]
            ),
        ),
        migrations.RunPython(
            code=copy_fields,
            reverse_code=reverse_copy_fields,
        ),
        migrations.RemoveField(
            model_name="account",
            name="allocated_leaves",
        ),
        migrations.AlterField(
            model_name="account",
            name="current_year_allocated_leaves",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(365)]
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="default_allocated_leaves",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(365)]
            ),
        ),
    ]
