# Generated by Django 6.0.2 on 2026-02-09 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_calendar', '0002_alter_holiday_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holidays_deleted', to=settings.AUTH_USER_MODEL),
        ),
    ]
