# Generated by Django 6.0.2 on 2026-02-09 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_calendar', '0003_alter_holiday_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekoff',
            old_name='modified_on',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='weekoff',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='weekoff',
            name='created_by',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.PROTECT, related_name='weekoffs_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
