# Generated by Django 6.0.2 on 2026-02-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_calendar', '0004_rename_modified_on_weekoff_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekoff',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='weekoff',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='weekoff',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='weekoff',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='weekoff',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='weekoff',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='weekoff',
            name='wednesday',
        ),
        migrations.RemoveField(
            model_name='weekoff',
            name='week_of_month',
        ),
        migrations.AddField(
            model_name='weekoff',
            name='day',
            field=models.CharField(blank=True, choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='weekoff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='weekoff',
            name='weeks',
            field=models.JSONField(default=list),
        ),
    ]
