# Generated by Django 6.0.2 on 2026-02-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_calendar', '0005_remove_weekoff_friday_remove_weekoff_monday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekoff',
            name='day',
            field=models.CharField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10, unique=True),
        ),
    ]
