# Generated by Django 6.0.2 on 2026-02-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_created_by_leave_deleted_by_leave_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='number_of_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
